### ISSUE TITLE
windows 10 python 2.7 

### ISSUE THREAD

**Issue by oren-cybereason** [yonatan-mitmit/onium#1]
Hi when running this on windows 10 from command line I get the issue :
C:\WINDOWS\system32>onium
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\onium.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\onium\__init__.py", line 248, in main
    kill_existing_slack()
  File "c:\python27\lib\site-packages\onium\__init__.py", line 170, in kill_existing_slack
    name = os.path.splitext(i.name())[0]
  File "c:\python27\lib\site-packages\psutil\__init__.py", line 505, in name
    name = self._proc.name()
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 207, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 241, in name
    return os.path.basename(self.exe())
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 213, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: (pid=120)

**Comment by yonatan-mitmit** [comment]
This error means that Onium can't kill the existing Slack process and is getting AccessDenied. Are you running slack elevated?
Agree the error message can be a bit clearer :)

**Comment by yonatan-mitmit** [comment]
Resolved in 0.3.3
Thanks.
